# Generated by Django 3.0.3 on 2020-02-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True)),
                ('des', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
