# Generated by Django 3.0.3 on 2020-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('cate', models.CharField(blank=True, max_length=100, null=True)),
                ('subcate', models.CharField(blank=True, max_length=100, null=True)),
                ('location_title', models.CharField(blank=True, max_length=100, null=True)),
                ('des', models.CharField(blank=True, max_length=100, null=True)),
                ('img1', models.ImageField(upload_to='images/')),
                ('img2', models.ImageField(upload_to='images/')),
                ('img3', models.ImageField(upload_to='images/')),
                ('img4', models.ImageField(upload_to='images/')),
                ('v_status', models.IntegerField(blank=True, null=True)),
                ('info', models.CharField(blank=True, max_length=100, null=True)),
                ('vid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'loaction',
            },
        ),
    ]
