# Generated by Django 3.0.3 on 2020-05-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='map',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
