# Generated by Django 3.0.3 on 2020-02-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('findusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registration',
        ),
    ]
